### ISSUE TITLE
有效问题

### ISSUE THREAD

**Issue by reporter-law** [tian0zhi/Orderseat#1]
好像用不了啊!

**Comment by tian0zhi** [comment]
哦，不好意思，如果确实不能用的话可能是因为“来选座”更改了他的业务逻辑，这个程序是去年9月份的，我已经好久没有分析“来选座”了。

**Comment by tian0zhi** [comment]
> 好像用不了啊!
哦，不好意思，如果确实不能用的话可能是因为“来选座”更改了他的业务逻辑，这个程序是去年9月份的，我已经好久没有分析“来选座”了。
